title: infoqoch's
tagline: 개발 블로그
author:
  name: infoqoch
  url: https://infoqoch.github.io
  
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Build Settings

paginate: 30

tags_path: /tags/
categories_path: /categories/