title: infoqoch blog
tagline: Personal Blog Page
author:
  name: infoqoch
  url: infoqoch.github.io

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Build Settings

paginate: 5

tags_path: /tags/
categories_path: /categories/
